"""
AERIS Report Generator Tool
Creates structured reports from data/text and saves them to disk.
Supports: .txt, .md (Markdown), .html formats — no external dependencies needed.
For PDF: uses reportlab if available, falls back to .txt.

Usage:
- params["title"]: Report title
- params["content"]: Dict or string content (from scraper, memory, etc.)
- params["path"]: Save path (default: user's Desktop or C:/AERIS_Reports/)
- params["format"]: "txt", "md", "html", "pdf" (default: "md")
"""

import os
import time
import json
import logging
from datetime import datetime
from services.tool_base import Tool, ToolResult

logger = logging.getLogger(__name__)

DEFAULT_REPORT_DIR = os.path.join(os.path.expanduser("~"), "Desktop", "AERIS_Reports")


class ReportGeneratorTool(Tool):
    name = "report_generator"
    description = "Generate structured reports from data and save to disk"
    requires_confirmation = False
    capabilities = ["generate_report", "report", "create_report", "save_report"]

    def execute(self, params: dict) -> ToolResult:
        start_time = time.time()

        title = params.get("title", "AERIS Report")
        content = params.get("content", "")
        path = params.get("path", "")
        fmt = params.get("format", "md").lower().strip(".")
        source_url = params.get("source_url", "")

        # Resolve the output path
        if not path:
            os.makedirs(DEFAULT_REPORT_DIR, exist_ok=True)
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            safe_title = "".join(c for c in title if c.isalnum() or c in " _-")[:30].strip().replace(" ", "_")
            filename = f"{safe_title}_{timestamp}.{fmt}"
            path = os.path.join(DEFAULT_REPORT_DIR, filename)
        else:
            # Ensure directory exists
            out_dir = os.path.dirname(path)
            if out_dir:
                os.makedirs(out_dir, exist_ok=True)
            # Add extension if missing
            if not path.endswith(f".{fmt}"):
                path = f"{path}.{fmt}"

        # Format content
        try:
            if fmt == "md":
                report_text = self._format_markdown(title, content, source_url)
            elif fmt == "html":
                report_text = self._format_html(title, content, source_url)
            elif fmt == "pdf":
                return self._write_pdf(title, content, path, source_url, start_time)
            else:  # txt fallback
                report_text = self._format_text(title, content, source_url)

            with open(path, "w", encoding="utf-8") as f:
                f.write(report_text)

            execution_time = time.time() - start_time
            return ToolResult(
                success=True,
                data={
                    "saved_to": path,
                    "format": fmt,
                    "title": title,
                    "size_bytes": len(report_text.encode("utf-8")),
                    "lines": report_text.count("\n")
                },
                meta={"tool": self.name, "execution_time": execution_time}
            )

        except Exception as e:
            logger.error(f"[ReportGeneratorTool] Error: {e}")
            return ToolResult(
                success=False,
                error=f"Failed to generate report: {str(e)}",
                meta={"tool": self.name, "execution_time": time.time() - start_time}
            )

    # ------------------------------------------------------------------
    # Format renderers
    # ------------------------------------------------------------------

    def _format_markdown(self, title: str, content, source_url: str) -> str:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = [
            f"# {title}",
            f"",
            f"> **Generated by AERIS** | {now}",
            f"",
        ]
        if source_url:
            lines += [f"> **Source:** {source_url}", ""]

        lines.append("---")
        lines.append("")

        if isinstance(content, dict):
            # Structured content from web scraper
            if content.get("title"):
                lines += [f"## Page Title", f"{content['title']}", ""]

            if content.get("meta_description"):
                lines += [f"**Summary:** {content['meta_description']}", ""]

            if content.get("headings"):
                lines += ["## Contents", ""]
                for h in content["headings"][:15]:
                    indent = "  " * (int(h["level"][1]) - 1)
                    lines.append(f"{indent}- {h['text']}")
                lines.append("")

            if content.get("paragraphs"):
                lines += ["## Key Information", ""]
                for p in content["paragraphs"][:20]:
                    lines += [p, ""]

            if content.get("tables"):
                lines += ["## Data Tables", ""]
                for i, table in enumerate(content["tables"][:3]):
                    if table:
                        header = table[0]
                        lines.append("| " + " | ".join(header) + " |")
                        lines.append("| " + " | ".join(["---"] * len(header)) + " |")
                        for row in table[1:10]:
                            lines.append("| " + " | ".join(str(c) for c in row) + " |")
                        lines.append("")

            if content.get("links"):
                lines += ["## Related Links", ""]
                for link in content["links"][:10]:
                    lines.append(f"- [{link['text']}]({link['url']})")
                lines.append("")

        elif isinstance(content, str):
            lines += [content, ""]
        else:
            lines += [str(content), ""]

        lines += ["---", f"*Report generated by AERIS — {now}*"]
        return "\n".join(lines)

    def _format_text(self, title: str, content, source_url: str) -> str:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        sep = "=" * 60
        lines = [
            sep,
            f"  {title.upper()}",
            f"  Generated by AERIS | {now}",
        ]
        if source_url:
            lines.append(f"  Source: {source_url}")
        lines += [sep, ""]

        if isinstance(content, dict):
            if content.get("title"):
                lines += [f"PAGE TITLE: {content['title']}", ""]
            if content.get("paragraphs"):
                lines += ["CONTENT:", ""]
                for p in content["paragraphs"][:20]:
                    lines += [p, ""]
            if content.get("plain_text"):
                lines += ["FULL TEXT:", "", content["plain_text"][:3000], ""]
        else:
            lines += [str(content), ""]

        lines += [sep, f"End of Report — {now}"]
        return "\n".join(lines)

    def _format_html(self, title: str, content, source_url: str) -> str:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        paragraphs_html = ""
        if isinstance(content, dict):
            for p in content.get("paragraphs", [])[:20]:
                paragraphs_html += f"<p>{p}</p>\n"
            body_title = content.get("title", "")
        else:
            paragraphs_html = f"<p>{content}</p>"
            body_title = ""

        source_html = f'<p><strong>Source:</strong> <a href="{source_url}">{source_url}</a></p>' if source_url else ""

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #222; }}
  h1 {{ color: #1a1a2e; border-bottom: 2px solid #e0e0e0; padding-bottom: 10px; }}
  h2 {{ color: #16213e; }}
  .meta {{ background: #f0f4ff; border-left: 4px solid #4a90d9; padding: 10px 16px; margin: 20px 0; font-size: 0.9em; }}
  p {{ line-height: 1.7; }}
  footer {{ margin-top: 40px; border-top: 1px solid #e0e0e0; padding-top: 10px; font-size: 0.8em; color: #999; }}
</style>
</head>
<body>
<h1>{title}</h1>
<div class="meta">
  <strong>Generated by AERIS</strong> | {now}<br>
  {source_html}
</div>
{f'<h2>{body_title}</h2>' if body_title else ''}
{paragraphs_html}
<footer>Report generated by AERIS — {now}</footer>
</body>
</html>"""

    def _write_pdf(self, title: str, content, path: str, source_url: str, start_time: float) -> ToolResult:
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import getSampleStyleSheet
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
            from reportlab.lib.units import inch

            doc = SimpleDocTemplate(path, pagesize=letter)
            styles = getSampleStyleSheet()
            story = []
            story.append(Paragraph(title, styles["Title"]))
            story.append(Spacer(1, 0.2 * inch))

            if isinstance(content, dict):
                for p in content.get("paragraphs", [])[:20]:
                    story.append(Paragraph(p, styles["Normal"]))
                    story.append(Spacer(1, 0.1 * inch))
            else:
                story.append(Paragraph(str(content), styles["Normal"]))

            doc.build(story)

            return ToolResult(
                success=True,
                data={"saved_to": path, "format": "pdf", "title": title},
                meta={"tool": self.name, "execution_time": time.time() - start_time}
            )
        except ImportError:
            # Fallback to markdown if reportlab not available
            logger.warning("[ReportGeneratorTool] reportlab not found, falling back to .md")
            path = path.replace(".pdf", ".md")
            text = self._format_markdown(title, content, source_url)
            with open(path, "w", encoding="utf-8") as f:
                f.write(text)
            return ToolResult(
                success=True,
                data={"saved_to": path, "format": "md", "note": "PDF not available, saved as Markdown"},
                meta={"tool": self.name, "execution_time": time.time() - start_time}
            )
        except Exception as e:
            return ToolResult(
                success=False,
                error=f"PDF generation failed: {e}",
                meta={"tool": self.name, "execution_time": time.time() - start_time}
            )
